### PR TITLE
fix: use asPath instead of route for shallowRouting comparison

### LINKED ISSUE #82: isSameURLWithoutSearch Bug
After merging https://github.com/Skyleen77/next-nprogress-bar/pull/81 I ran test with `shallowRouting` and `disableSameURL`.

It works to the exception of routes which have variable parameters in there.

The issue is with this logic:
https://github.com/Skyleen77/next-nprogress-bar/blob/main/src/PagesProgressBar.tsx#L54C1-L55C65

`Router.route` returns the template version of the route while the href contains the templated version:
```json
{
  "currentUrl": "http://localhost:3000/posts/[postId]"
  "targetUrl": "http://localhost:3000/posts/de64b4ce-cc79-443b-975b-c886fffa7cf1"
}

### PR DESCRIPTION
**Pull request by l0gicgate**
Closes #82 

After merging https://github.com/Skyleen77/next-nprogress-bar/pull/81 I ran test with `shallowRouting` and `disableSameURL`.

It works to the exception of routes which have variable parameters in there.

The issue is with this logic:
https://github.com/Skyleen77/next-nprogress-bar/blob/50aae80d4207addea77e9bb082cdee49b44ab283/src/PagesProgressBar.tsx#L54C1-L55C65

`Router.route` returns the template version of the route while the href contains the templated version:
```json
{
  "currentUrl": "http://localhost:3000/posts/[postId]"
  "targetUrl": "http://localhost:3000/posts/de64b4ce-cc79-443b-975b-c886fffa7cf1"
}

### CODE REVIEW

**Comment by l0gicgate** [comment]
@Skyleen77 can you take a look at this PR soon as you can please 🙏🏼

File: src/PagesProgressBar.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ export const PagesProgressBar = React.memo(
 
       const handleRouteStart = (url: string) => {
         const targetUrl = new URL(url, location.href);
-        const currentUrl = new URL(Router.route, location.href);
+        const currentUrl = new URL(Router.asPath, location.href);
```
Comment (alexjamesmacpherson) [inline src/PagesProgressBar.tsx:55]: i've observed that this still doesn't work when the application is configured to have a `basePath`, and i suspect it may not work if the app has a locale in the url as well

this is because the `targetUrl` will have the configured `basePath` and current locale (if non-default) encoded into the pathname of its url, but the `currentUrl` will not because `Router.asPath` omits both `basePath` and locale (see docs: https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object), meaning the equality check will not match

ideally this method could be updated to handle the `basePath` configuration, as well as the existence (or lack thereof) of a locale in the pathname - all of this information should be readable from the `Router` object to my knowledge, so hopefully not too complex

handling `basePath` may be as simple as just prefixing it to `Router.asPath` - eg:
```suggestion
        const currentUrl = new URL(`${Router.basePath}${Router.asPath}`, location.href);
```

but handling non-default locales may be more complex 🤔

Comment (alexjamesmacpherson) [reply src/PagesProgressBar.tsx:55]: in fact, is it insufficient to just use `location.href` directly for the current URL? do we need to read anything from the router config? `location.href` should have everything we need already encoded (e.g. `basePath`, locale, etc.) - is there a particular reason for interpreting the URL from the router instead?
```suggestion
        const currentUrl = new URL(location.href);
```

Comment (l0gicgate) [reply src/PagesProgressBar.tsx:55]: Those are great observations. I actually just noticed that `location.href` is used in the `AppProgressBar` for this comparison:

https://github.com/Skyleen77/next-nprogress-bar/blob/50aae80d4207addea77e9bb082cdee49b44ab283/src/AppProgressBar.tsx#L132

I've applied your suggestion!

**Comment by l0gicgate** [comment]
@Skyleen77 bumping this. Please take a look when you can 🙏🏼

**Comment by Skyleen77** [comment]
You can now update to the 2.4.3 :)
